# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Budgety-WalletApp' do

use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
